FROM nginx
COPY html /usr/share/nginx/html
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# RUN echo "server { listen 8888; server_name example.com; }" >> /etc/nginx/conf.d/default.conf
# COPY default.conf /etc/nginx/conf.d/