version: '3'

services:
  web:
    image: node:14
    depends_on:
      - db
    ports:
      - 3000:3000
    working_dir: /app
    command: node index.js
    environment:
      - DB_HOST=db 
      - DB_PORT=3306
    networks:
      - my_network

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - my_network

networks:
  my_network: